spec:
  volumes:
  - name: home
    projected:
      sources:
      - secret:
          name: maven-settings
          items:
            - key: settings-security.xml
              path: ".m2/settings-security.xml"
      - configMap:
          name: maven-settings
          items:
            - key: settings.xml
              path: ".m2/settings.xml"
      - configMap:
          name: npm-config
  - name: cache
    hostPath:
      path: "/var/tmp/build-cache"
  imagePullSecrets:
  - name: registry-cred
  containers:
  - name: maven
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    volumeMounts:
    - mountPath: "/home/build"
      name: home
    - mountPath: "/cache"
      name: cache
    image: registry.dev.yashkov.org/yashkov/maven:3.8.4-jdk17
    imagePullPolicy: Always
    resources:
      requests:
        memory: 1024Mi
        cpu: 100m
      limits:
        memory: 1200Mi
        cpu: 500m
    env:
    - name: HOME
      value: "/home/build"
    - name: JAVA_TOOL_OPTIONS
      value: "-XX:MaxRAMPercentage=15 -Duser.home=/home/build"
    command:
    - "/bin/cat"
    tty: true
