---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: dev
  name: nexus
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: dev
  name: nexus-transient
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: dev
  name: nexus-releases
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: dev
  name: nexus
  labels:
    app: nexus
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nexus
      - name: transient
        persistentVolumeClaim:
          claimName: nexus-transient
      - name: releases
        persistentVolumeClaim:
          claimName: nexus-releases
      initContainers:
      - name: nexus-volumes
        image: alpine:3.15.0
        volumeMounts:
        - mountPath: "/nexus-data"
          name: data
        - mountPath: "/nexus-transient"
          name: transient
        - mountPath: "/nexus-releases"
          name: releases
        command:
        - "chown"
        - "200:200"
        - "/nexus-data"
        - "/nexus-transient"
        - "/nexus-releases"
      containers:
      - name: nexus
        image: sonatype/nexus3:3.37.3
        volumeMounts:
        - mountPath: "/nexus-data"
          name: data
        - mountPath: "/nexus-transient"
          name: transient
        - mountPath: "/nexus-releases"
          name: releases
        env:
        - name: INSTALL4J_ADD_VM_PARAMS
          value: "-Xms512m -Xmx1200m -XX:MaxDirectMemorySize=2g -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs"
        ports:
        - containerPort: 8081
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 580Mi
          limits:
            cpu: 500m
            memory: 1300Mi

---
kind: Service
apiVersion: v1
metadata:
  namespace: dev
  name: repo
  labels:
    app: nexus
spec:
  type: ClusterIP
  selector:
    app: nexus
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081
  - name: docker
    protocol: TCP
    port: 5000
    targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dev
  name: repo
  labels:
    app: nexus
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "lets-encrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
  - hosts:
    - repo.dev.yashkov.org
    secretName: repo-dev-yashkov-org-ingress
  rules:
  - host: repo.dev.yashkov.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: repo
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dev
  name: registry
  labels:
    app: registry
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "lets-encrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
  - hosts:
    - registry.dev.yashkov.org
    secretName: registry-dev-yashkov-org-ingress
  rules:
  - host: registry.dev.yashkov.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: repo
            port:
              number: 5000
