apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: lets-encrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: alexei.yashkov@yashkov.org
    privateKeySecretRef:
      name: lets-encrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
