spec:
  volumes:
  - name: maven
    projected:
      sources:
      - secret:
          name: maven-settings
      - configMap:
          name: maven-settings
  - name: npm
    configMap:
      name: npm-config
  - name: home
    emptyDir:
      medium: ""
  - name: tmp
    hostPath:
      path: "/var/tmp"
  imagePullSecrets:
  - name: registry-cred
  containers:
  - name: maven
    securityContext:
      capabilities:
        add:
        - "SYS_ADMIN"
    volumeMounts:
    - mountPath: "/home/build"
      name: home
    - mountPath: "/home/build/.m2"
      name: maven
    - mountPath: "/home/build/.npmrc"
      name: npm
      subPath: .npmrc
    - mountPath: "/var/tmp"
      name: tmp
    image: registry.dev.yashkov.org/yashkov/maven:3.8.3.3
    imagePullPolicy: Always
    resources:
      requests:
        memory: 1024Mi
        cpu: 100m
      limits:
        memory: 1200Mi
        cpu: 500m
    env:
    - name: JAVA_TOOL_OPTIONS
      value: "-XX:MaxRAMPercentage=15"
    command:
    - "/bin/cat"
    tty: true
