apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.httpPort }}
    targetPort: http
  - name: jnlp
    protocol: TCP
    port: {{ .Values.service.jnlpPort }}
    targetPort: jnlp
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}
