---
kind: Namespace
apiVersion: v1
metadata:
  name: dev

---
kind: LimitRange
apiVersion: v1
metadata:
  namespace: dev
  name: limits
spec:
  limits:
  - type: Container
    default:
      cpu: 250m
      memory: 256Mi
    defaultRequest:
      cpu: 50m
      memory: 256Mi
