---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: dev
  name: registry
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: dev
  name: registry
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      volumes:
      - name: registry
        persistentVolumeClaim:
          claimName: registry
      containers:
      - name: registry
        image: registry:2.7.1
        volumeMounts:
        - mountPath: "/var/lib/registry"
          name: registry
        ports:
        - containerPort: 5000
  replicas: 1

---
kind: Service
apiVersion: v1
metadata:
  namespace: dev
  name: registry
  labels:
    app: registry
spec:
  type: ClusterIP
  selector:
    app: registry
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
