---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: dev
  name: registry
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: dev
  name: registry
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      volumes:
      - name: registry
        persistentVolumeClaim:
          claimName: registry
      - name: certs
        secret:
          secretName: registry-cert
      containers:
      - name: registry
        image: registry:2.7.1
        volumeMounts:
        - mountPath: "/var/lib/registry"
          name: registry
        - mountPath: "/etc/certs"
          name: certs
        env:
        - name: "REGISTRY_HTTP_ADDR"
          value: "0.0.0.0:5433"
        - name: "REGISTRY_HTTP_TLS_CERTIFICATE"
          value: "/etc/certs/tls.crt"
        - name: "REGISTRY_HTTP_TLS_KEY"
          value: "/etc/certs/tls.key"
        ports:
        - containerPort: 5433
  replicas: 1

---
kind: Service
apiVersion: v1
metadata:
  namespace: dev
  name: registry
  labels:
    app: registry
spec:
  type: ClusterIP
  selector:
    app: registry
  ports:
  - name: https
    protocol: TCP
    port: 5433
    targetPort: 5433
