# Default values for gitea.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# export POSTGRES_PASSWORD=$(kubectl get secret --namespace "dev" gitea-postgresql -o jsonpath="{.data.postgres-password}" | base64 -d)
# helm upgrade gitea gitea/gitea -f src/config/gitea.yaml --set gitea.admin.password=XXXXXXXX --set postgresql.global.postgresql.auth.password=XXXXXXXX --set global.postgresql.auth.postgresPassword=$POSTGRES_PASSWORD

global:
  storageClass: do-block-storage

image:
  rootless: true

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hosts:
    - host: gitea.dev.yashkov.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gitea-dev-yashkov-org-tls
      hosts:
        - gitea.dev.yashkov.org

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

persistence:
  size: 10Gi

## @section Gitea
#
gitea:
  admin:
    username: gitea
    password: <REPLACE>
    email: alexei.yashkov@yashkov.org
  config:
    service:
      DISABLE_REGISTRATION: true

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        database: gitea
        username: gitea
        password: <REPLACE>
      service:
        ports:
          postgresql: 5432
  primary:
    persistence:
      size: 2Gi
