imagePullSecrets:
  - name: registry-cred

storage:
  className: do-block-storage
  request: 2Gi

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt-prod
  domain: dev.yashkov.org
  tlsSecret: jenkins-dev-yashkov-org-tls
