pod:
  imagePullSecrets:
    - name: registry-cred

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt-prod
  hosts:
    - yashkov.org
    - www.yashkov.org
  domain: ""
  tlsSecret: yashkov-org-tls

replicaCount: 2
