apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-site.fullname" . }}
  labels:
    {{- include "web-site.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "web-site.selectorLabels" . | nindent 4 }}
