---
kind: LimitRange
apiVersion: v1
metadata:
  namespace: default
  name: limits
spec:
  limits:
  - type: Container
    default:
      cpu: 250m
      memory: 110Mi
    defaultRequest:
      cpu: 50m
      memory: 100Mi
