---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: www
  labels:
    app: www
spec:
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      imagePullSecrets:
      - name: registry-cred
      containers:
      - name: www
        image: registry.dev.yashkov.org/yashkov/web-site:40
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
  replicas: 2

---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: www
  labels:
    app: www
spec:
  type: ClusterIP
  selector:
    app: www
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: www
  labels:
    app: www
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "lets-encrypt-prod"
spec:
  tls:
  - hosts:
    - yashkov.org
    - www.yashkov.org
    secretName: yashkov-org-ingress
  rules:
  - host: yashkov.org
    http:
      paths:
      - path: /
        backend:
          serviceName: www
          servicePort: 80
  - host: www.yashkov.org
    http:
      paths:
      - path: /
        backend:
          serviceName: www
          servicePort: 80
