---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: www
  labels:
    app: www
spec:
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: www
        # image: registry.dev.svc.cluster.local/yashkov/web-site:9
        image: nginx
        ports:
        - containerPort: 80
      - name: debug
        image: alpine:3.11.3
        tty: true
        command:
        - cat
  replicas: 1

---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: www
  labels:
    app: www
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "le-yashkov-org"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  selector:
    app: www
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 80
